language: node_js
node_js:
  - '9'
cache: ~/.npm

branches:
  only:
    - master

install:
  - npm install

stages:
  - lint
  - test
  - codecov
  - changelog
  - deploy to production

jobs:
  include:
    - stage: lint
      script: npm run lint && npm run format
    - stage: test
      script: npm run test
    - stage: codecov
      script: npx codecov --token=$CODECOV_TOKEN
    - stage: changelog
      script: npx semantic-release
    - stage: deploy to production
      script: npm run build:doc
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          local-dir: ./docs
