language: node_js
node_js:
  - '9'
cache: ~/.npm

install:
  - npm install

stages:
  - lint
  - test
  - codecov
  - release
  - deploy doc site

jobs:
  include:
    - stage: lint
      script: npm run lint && npm run format
    - stage: test
      script: npm run test
    - stage: codecov
      script: npm run test && npx codecov --token=$CODECOV_TOKEN
    - stage: release
      if: branch = master
      if: type != pull_request
      script: npm run build && npx semantic-release
    - stage: deploy doc site
      script: npm run build:doc && touch ./docs/.nojekyll
      if: branch = master
      if: type != pull_request
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          local-dir: ./docs
